-- Drop table AISTUDENTTESTER.TESTSESSION
DROP TABLE IF EXISTS AISTUDENTTESTER.TESTSESSION;

-- Drop table AISTUDENTTESTER.MARK
DROP TABLE IF EXISTS AISTUDENTTESTER.MARK;

-- Drop table AISTUDENTTESTER.STRATEGY
DROP TABLE IF EXISTS AISTUDENTTESTER.STRATEGY;

-- Drop table AISTUDENTTESTER.STUDENT
DROP TABLE IF EXISTS AISTUDENTTESTER.STUDENT;

-- Drop table AISTUDENTTESTER.STUDENTGROUP
DROP TABLE IF EXISTS AISTUDENTTESTER.STUDENTGROUP;

-- Drop table AISTUDENTTESTER.ROLEMAP
DROP TABLE IF EXISTS AISTUDENTTESTER.ROLEMAP;

-- Drop table AISTUDENTTESTER.APPLICATIONUSER
DROP TABLE IF EXISTS AISTUDENTTESTER.APPLICATIONUSER;

-- Drop table AISTUDENTTESTER.ROLE
DROP TABLE IF EXISTS AISTUDENTTESTER.ROLE;

-- Drop table AISTUDENTTESTER.QUESTIONMAPQUESTIONMAP
DROP TABLE IF EXISTS AISTUDENTTESTER.QUESTIONMAP;

-- Drop table AISTUDENTTESTER.TOPIC
DROP TABLE IF EXISTS AISTUDENTTESTER.TOPIC;

-- Drop table AISTUDENTTESTER.SUBJECT
DROP TABLE IF EXISTS AISTUDENTTESTER.SUBJECT;

-- Drop table AISTUDENTTESTER.QUESTION
DROP TABLE IF EXISTS AISTUDENTTESTER.QUESTION;

-- Drop database AISTUDENTTESTER
DROP DATABASE IF EXISTS AISTUDENTTESTER;