-- Insert data to table AISTUDENTTESTER.ROLE
INSERT INTO AISTUDENTTESTER.ROLE (ROLENAME, ACTIVEFLAG)
VALUES ('USER', 'Y');
INSERT INTO AISTUDENTTESTER.ROLE (ROLENAME, ACTIVEFLAG)
VALUES ('ADMIN', 'Y');









-- Drop table AISTUDENTTESTER.TESTSESSION

-- Drop table AISTUDENTTESTER.MARK

-- Drop table AISTUDENTTESTER.STRATEGY

-- Drop table AISTUDENTTESTER.STUDENT

-- Drop table AISTUDENTTESTER.STUDENTGROUP

-- Drop table AISTUDENTTESTER.ROLEMAP

-- Drop table AISTUDENTTESTER.APPLICATIONUSER



-- Drop table AISTUDENTTESTER.QUESTIONMAPQUESTIONMAP

-- Drop table AISTUDENTTESTER.TOPIC

-- Drop table AISTUDENTTESTER.SUBJECT

-- Drop table AISTUDENTTESTER.QUESTION

-- Drop database AISTUDENTTESTER
