-- Insert data to table AISTUDENTTESTER.ROLE
INSERT INTO AISTUDENTTESTER.ROLE (ROLENAME, ACTIVEFLAG)
VALUES ('USER', 'Y');
INSERT INTO AISTUDENTTESTER.ROLE (ROLENAME, ACTIVEFLAG)
VALUES ('ADMIN', 'Y');

-- Insert data to table AISTUDENTTESTER.STRATEGY
INSERT INTO AISTUDENTTESTER.STRATEGY (STRATEGYNAME, ACTIVEFLAG)
VALUES ('SIMPLE', 'Y');
INSERT INTO AISTUDENTTESTER.STRATEGY (STRATEGYNAME, ACTIVEFLAG)
VALUES ('MULTI', 'N');





-- Drop table AISTUDENTTESTER.TESTSESSION

-- Drop table AISTUDENTTESTER.MARK

-- Drop table AISTUDENTTESTER.STUDENT

-- Drop table AISTUDENTTESTER.STUDENTGROUP

-- Drop table AISTUDENTTESTER.ROLEMAP

-- Drop table AISTUDENTTESTER.APPLICATIONUSER



-- Drop table AISTUDENTTESTER.QUESTIONMAPQUESTIONMAP

-- Drop table AISTUDENTTESTER.TOPIC

-- Drop table AISTUDENTTESTER.SUBJECT

-- Drop table AISTUDENTTESTER.QUESTION

-- Drop database AISTUDENTTESTER
