-- Insert data to table AISTUDENTTESTER.QUESTIONMAP

-- Topic 1
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (1, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (2, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (3, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (4, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (5, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (6, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (7, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (8, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (9, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (10, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (11, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (12, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (13, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (14, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (15, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (16, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (17, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (18, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (19, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (20, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (21, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (22, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (23, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (24, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (25, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (26, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (27, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (28, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (29, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (30, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (31, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (32, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (33, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (34, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (35, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (36, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (37, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (38, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (39, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (40, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (41, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (42, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (43, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (44, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (45, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (46, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (47, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (48, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (49, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (50, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (51, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (52, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (53, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (54, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (55, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (56, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (57, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (58, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (59, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (60, 1, 'Y');

-- Topic 2
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (61, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (62, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (63, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (64, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (65, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (66, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (67, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (68, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (69, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (70, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (71, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (72, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (73, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (74, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (75, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (76, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (77, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (78, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (79, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (80, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (81, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (82, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (83, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (84, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (85, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (86, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (87, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (88, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (89, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (90, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (91, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (92, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (93, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (94, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (95, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (96, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (97, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (98, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (99, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (100, 2, 'Y');

-- Topic 3
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (101, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (102, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (103, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (104, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (105, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (106, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (107, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (108, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (109, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (110, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (111, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (112, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (113, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (114, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (115, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (116, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (117, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (118, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (119, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (120, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (121, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (122, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (123, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (124, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (125, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (126, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (127, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (128, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (129, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (130, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (131, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (132, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (133, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (134, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (135, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (136, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (137, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (138, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (139, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (140, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (141, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (142, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (143, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (144, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (145, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (146, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (147, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (148, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (149, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (150, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (151, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (152, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (153, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (154, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (155, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (156, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (157, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (158, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (159, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (160, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (161, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (162, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (163, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (164, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (165, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (166, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (167, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (168, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (169, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (170, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (171, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (172, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (173, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (174, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (175, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (176, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (177, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (178, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (179, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (180, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (181, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (182, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (183, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (184, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (185, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (186, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (187, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (188, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (189, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (190, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (191, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (192, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (193, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (194, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (195, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (196, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (197, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (198, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (199, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (200, 3, 'Y');