-- Insert data to table AISTUDENTTESTER.QUESTIONMAP

-- Topic 1
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (1, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (2, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (3, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (4, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (5, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (6, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (7, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (8, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (9, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (10, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (11, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (12, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (13, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (14, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (15, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (16, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (17, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (18, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (19, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (20, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (21, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (22, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (23, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (24, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (25, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (26, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (27, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (28, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (29, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (30, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (31, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (32, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (33, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (34, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (35, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (36, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (37, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (38, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (39, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (40, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (41, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (42, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (43, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (44, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (45, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (46, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (47, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (48, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (49, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (50, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (51, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (52, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (53, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (54, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (55, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (56, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (57, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (58, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (59, 1, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (60, 1, 'Y');

-- Topic 2
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (61, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (62, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (63, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (64, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (65, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (66, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (67, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (68, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (69, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (70, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (71, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (72, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (73, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (74, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (75, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (76, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (77, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (78, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (79, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (80, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (81, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (82, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (83, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (84, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (85, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (86, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (87, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (88, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (89, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (90, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (91, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (92, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (93, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (94, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (95, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (96, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (97, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (98, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (99, 2, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (100, 2, 'Y');

-- Topic 3
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (101, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (102, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (103, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (104, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (105, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (106, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (107, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (108, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (109, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (110, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (111, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (112, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (113, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (114, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (115, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (116, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (117, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (118, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (119, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (120, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (121, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (122, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (123, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (124, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (125, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (126, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (127, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (128, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (129, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (130, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (131, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (132, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (133, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (134, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (135, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (136, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (137, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (138, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (139, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (140, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (141, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (142, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (143, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (144, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (145, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (146, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (147, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (148, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (149, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (150, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (151, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (152, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (153, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (154, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (155, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (156, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (157, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (158, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (159, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (160, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (161, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (162, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (163, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (164, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (165, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (166, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (167, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (168, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (169, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (170, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (171, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (172, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (173, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (174, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (175, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (176, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (177, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (178, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (179, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (180, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (181, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (182, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (183, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (184, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (185, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (186, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (187, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (188, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (189, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (190, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (191, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (192, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (193, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (194, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (195, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (196, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (197, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (198, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (199, 3, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (200, 3, 'Y');

-- Topic 4
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (201, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (202, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (203, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (204, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (205, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (206, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (207, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (208, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (209, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (210, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (211, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (212, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (213, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (214, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (215, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (216, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (217, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (218, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (219, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (220, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (221, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (222, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (223, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (224, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (225, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (226, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (227, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (228, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (229, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (230, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (231, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (232, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (233, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (234, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (235, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (236, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (237, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (238, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (239, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (240, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (241, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (242, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (243, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (244, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (245, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (246, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (247, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (248, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (249, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (250, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (251, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (252, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (253, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (254, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (255, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (256, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (257, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (258, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (259, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (260, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (261, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (262, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (263, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (264, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (265, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (266, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (267, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (268, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (269, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (270, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (271, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (272, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (273, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (274, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (275, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (276, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (277, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (278, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (279, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (280, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (281, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (282, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (283, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (284, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (285, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (286, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (287, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (288, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (289, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (290, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (291, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (292, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (293, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (294, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (295, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (296, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (297, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (298, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (299, 4, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (300, 4, 'Y');

-- Topic 5
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (301, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (302, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (303, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (304, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (305, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (306, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (307, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (308, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (309, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (310, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (311, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (312, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (313, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (314, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (315, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (316, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (317, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (318, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (319, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (320, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (321, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (322, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (323, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (324, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (325, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (326, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (327, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (328, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (329, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (330, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (331, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (332, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (333, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (334, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (335, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (336, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (337, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (338, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (339, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (340, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (341, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (342, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (343, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (344, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (345, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (346, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (347, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (348, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (349, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (350, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (351, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (352, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (353, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (354, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (355, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (356, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (357, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (358, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (359, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (360, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (361, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (362, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (363, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (364, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (365, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (366, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (367, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (368, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (369, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (370, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (371, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (372, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (373, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (374, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (375, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (376, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (377, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (378, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (379, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (380, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (381, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (382, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (383, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (384, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (385, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (386, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (387, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (388, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (389, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (390, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (391, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (392, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (393, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (394, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (395, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (396, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (397, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (398, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (399, 5, 'Y');
INSERT INTO AISTUDENTTESTER.QUESTIONMAP (QUESTIONID, TOPICID, ACTIVEFLAG)
VALUES (400, 5, 'Y');